### ISSUE TITLE
Inquiry about the availability for the visual data

### ISSUE THREAD

**Issue by TaoRuijie** [joonson/voxconverse#1]
Hi, thanks for your effort to build this VoxConverse database, really appreciate. 

I notice there are only audio files for development set, while VoxConverse is an audio-visual speaker diarization database, so will you plan to release the video files later?

Thanks for your time.

**Comment by joonson** [comment]
Hi, they will be released in some form, but this won’t be until after VoxSRC 2020.

**Comment by TaoRuijie** [comment]
Got it and thanks!
