### ISSUE TITLE
Error with voxconverse data download 

### ISSUE THREAD

**Issue by 009deep** [joonson/voxconverse#5]
I tried to download wav data from  [voxconverse](https://www.robots.ox.ac.uk/~vgg/data/voxconverse/) page. But, download always fails. How can I download  those wav files?

**Comment by JaesungHuh** [comment]
Hi.

I just tried downloading and it works for me. Could you give me your email address so I can send you the dev & test wav files?

Jaesung

**Comment by 009deep** [comment]
Thanks  for response.  Download seems inconsistent, it failed  quite a few times but  finally  I was  able to download. Thanks.
