### ISSUE TITLE
Can you share the video data?

### ISSUE THREAD

**Issue by bugdary** [joonson/voxconverse#6]
Can you please explain how to parse the labels ?

**Comment by JaesungHuh** [comment]
Thank you for question. As we've described in our paper, we used VIA annotator tool (https://www.robots.ox.ac.uk/~vgg/software/via/) for annotation. Sadly, we don't have a plan to share the video data.

**Comment by MessyPaste** [comment]
> Thank you for question. As we've described in our paper, we used VIA annotator tool (https://www.robots.ox.ac.uk/~vgg/software/via/) for annotation. Sadly, we don't have a plan to share the video data.

Do you have any plans to share the video URL from youtube?
