### ISSUE TITLE
Different folder for Version 0.2 and 0.3

### ISSUE THREAD

**Issue by AMITKESARI2000** [joonson/voxconverse#9]
Hi,
Thanks for the amazing reference data!
One suggestion would be to keep voxconverse 0.0.2 and 0.0.3 rttm files either in separate folders or branch, so that it can be compared with earlier reference papers as well in a standard way.
Thank you

**Comment by JaesungHuh** [comment]
This is a very good idea. I made a separate branch (ver 0.2) for people who want to see the previous version. Thank you for your suggestion.
